import os
import json
import numpy as np
from scipy.interpolate import interp1d

class MeshReader:
    '''
    path - path to the folder with set of NPZs and meta.json, generated by the main.py
    '''
    def __init__(self, path):
        self.mesh_path = path
        self.meta = json.load(open(os.path.join(path, 'meta.json')))
        self.files = []
        for f in os.scandir(path):
            if f.name.split('.')[-1] == 'npz':
                self.files.append(f.path)
        assert len(self.files) > 0, "No input files found!"

    
    def sample(self, speed, timestep_start, timestep_end):
        # Rescale to the input timesteps
        in_timestep_start = timestep_start / speed
        in_timestep_end = timestep_end / speed
        steps_overall = len(self.files) * self.meta['nt']
        load_step_start = int(in_timestep_start) % steps_overall
        load_step_end = int(in_timestep_end + 1) % steps_overall
        file_start = int(load_step_start / self.meta['nt'])
        file_end = int(load_step_end / self.meta['nt'])
        assert file_start >= 0 and file_start < len(self.files), "Wrong file index"
        assert file_end >= 0 and file_end < len(self.files), "Wrong file index"

        #Load the involved files
        fidx = file_start
        data = []
        while True:
            data.append(np.load(self.files[fidx])['arr_0'])
            if fidx == file_end:
                break
            fidx += 1
            if fidx == len(self.files):
                fidx = 0
        data = np.concatenate(data, axis=-1)

        # Interpolate
        old_time_start = self.meta['nt'] * file_start
        old_time_end = self.meta['nt'] * (file_end + 1)
        if old_time_end < old_time_start:
            old_time_end += steps_overall
        old_times = np.arange(old_time_start, old_time_end, 1) * speed
        new_times = np.arange(timestep_start, timestep_end, 1)
        interp = interp1d(
            old_times, data.reshape(-1, data.shape[-1]),
            axis=1,           # interpolate along the time axis
            kind='linear',    # 'linear', 'cubic', 'nearest', 'quadratic', ...
            assume_sorted=True,
        )
        resampled = interp(new_times)

        return resampled.reshape(data.shape[0], data.shape[1], data.shape[2], -1)


if __name__ == '__main__':
    reader = MeshReader('/app/input_mesh/test2')
    reader.sample(1.1, 300, 400)
    reader.sample(1.001, 16100, 16300)
