import os
import json
import numpy as np
from PIL import Image
from scipy.interpolate import interp1d

class MeshReader:
    '''
    path - path to the folder with set of NPZs and meta.json, generated by the main.py
    '''
    def __init__(self, path):
        self.mesh_path = path
        self.meta = json.load(open(os.path.join(path, 'meta.json')))
        self.files = []
        for f in os.scandir(path):
            if f.name.split('.')[-1] == 'npz':
                self.files.append(f.path)
        self.files = sorted(self.files)
        assert len(self.files) > 0, "No input files found!"

    
    def sample(self, speed, timestep_start, timestep_end):
        speed = 1 / speed   # So that speed of, e.g. 1.1 is faster, 0.9 is slower
        # Rescale to the input timesteps
        in_timestep_start = timestep_start / speed
        in_timestep_end = timestep_end / speed
        steps_overall = len(self.files) * self.meta['nt']
        load_step_start = int(in_timestep_start) % steps_overall
        load_step_end = int(in_timestep_end + 1) % steps_overall
        n_full_loops = int((in_timestep_end + 1 - in_timestep_start) / steps_overall)
        file_start = int(load_step_start / self.meta['nt'])
        file_end = int(load_step_end / self.meta['nt'])
        assert file_start >= 0 and file_start < len(self.files), "Wrong file index"
        assert file_end >= 0 and file_end < len(self.files), "Wrong file index"

        #Load the involved files
        fidx = file_start
        data = []
        n_loops_passed = 0
        while True:
            print('Loading file', self.files[fidx])
            data.append(np.load(self.files[fidx])['arr_0'])
            if fidx == file_end:
                if n_loops_passed >= n_full_loops:
                    break
            fidx += 1
            if fidx == len(self.files):
                fidx = 0
            if fidx == file_start:
                n_loops_passed += 1
        data = np.concatenate(data, axis=-1)

        # Interpolate
        old_time_start = self.meta['nt'] * file_start
        old_time_end = self.meta['nt'] * (file_end + 1 + n_full_loops * len(self.files))
        if old_time_end < old_time_start:
            old_time_end += steps_overall
        old_times = np.arange(old_time_start, old_time_end, 1) * speed
        new_times = np.arange(timestep_start, timestep_end, 1)
        while np.max(old_times) < np.max(new_times):
            old_times += steps_overall * speed
        assert np.min(old_times) <= np.min(new_times), "Wrong time scaling"
        assert np.max(old_times) >= np.max(new_times), "Wrong time scaling"
        interp = interp1d(
            old_times, data.reshape(-1, data.shape[-1]),
            axis=1,           # interpolate along the time axis
            kind='linear',    # 'linear', 'cubic', 'nearest', 'quadratic', ...
            assume_sorted=True,
        )
        resampled = interp(new_times)

        return resampled.reshape(data.shape[0], data.shape[1], data.shape[2], -1)


if __name__ == '__main__':
    reader = MeshReader('/app/input_mesh/test2')
    step = 400
    out_step = 15
    idx_start = 0

    images = None

    def process_images(imgs):
        global images
        if images is None:
            images = imgs
        else:
            images = np.concatenate([images, imgs], axis=0)
        
        pil_frames = [Image.fromarray(f) for f in images]
        pil_frames[0].save(
            '/app/speed_noise.gif',
            format="GIF",
            save_all=True,
            append_images=pil_frames[1:],
            duration=25,
            loop=0,
            optimize=True,
            disposal=2,
        )


    while idx_start < 50000:
        print("Processing index", idx_start)
        slow = reader.sample(0.95, idx_start, idx_start + step)[:, :, 8, ::out_step].real.astype(np.uint8)
        print('----')
        normal = reader.sample(1.0, idx_start, idx_start + step)[:, :, 8, ::out_step].real.astype(np.uint8)
        print('----')
        fast = reader.sample(1.05, idx_start, idx_start + step)[:, :, 8, ::out_step].real.astype(np.uint8)
        process_images(np.concatenate([slow, normal, fast], axis=1).transpose(2, 0, 1))
        idx_start += step
